Repository andela/ah-the-immortals-frontend, pull requests merged in 2019-06, with the labels that each got.

#12 #165305717 Signup User
  .babelrc
  .travis.yml
  jest.config.js
  package-lock.json
  package.json
  setupFiles.js
  src/App.jsx
  src/App.test.jsx
  src/components/home.jsx
  src/components/home/__tests__/__snapshots__/homeFooter.test.js.snap
  src/components/home/__tests__/__snapshots__/homeInfor.test.js.snap
  src/components/home/__tests__/__snapshots__/homeNavBar.test.js.snap
  src/components/home/__tests__/homeFooter.test.js
  src/components/home/__tests__/homeInfor.test.js
  src/components/home/__tests__/homeNavBar.test.js
  src/components/home/homeFooter.jsx
  src/components/home/homeInfo.jsx
  src/components/home/homeNavbar.jsx
  src/components/homeInfo.jsx
  src/components/homeNavbar.jsx
  src/components/loginInfo.jsx
  src/components/signup/FormComponent.jsx
  src/components/signup/SignupComponent.jsx
  src/components/signup/__tests__/FormComponent.test.js
  src/components/signup/__tests__/SignupComponent.test.js
  src/components/signup/__tests__/__snapshots__/FormComponent.test.js.snap
  src/index.html
  src/index.js
  src/redux/actions/SignUp.action.js
  src/redux/actions/__tests__/Signup.action.test.js
  src/redux/actions/sample.action.js 
  src/redux/constants/actionTypes.js
  src/redux/constants/constants.js
  src/redux/reducers/SignUp.reducer.js
  src/redux/reducers/__tests__/SignUpReducer.test.js
  src/redux/reducers/__tests__/sample.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/sample.reducer.js
  src/services/api.js
  src/services/images/facebook.png
  src/services/images/google.png
  src/services/images/twitter.png
  src/styles/App.css
  src/styles/style.css
  src/views/home/HomeContainer.jsx
  src/views/home/__tests__/__snapshots__/homeContainer.test.js.snap
  src/views/home/__tests__/homeContainer.test.js
  webpack.config.js
Labels: Reviews required

#20 #166492952 Fix Signup
  src/components/signup/SignupComponent.jsx
  src/styles/App.css
  src/styles/style.css
  src/views/home/HomeContainer.jsx
  src/views/home/__tests__/__snapshots__/homeContainer.test.js.snap
Labels: Work in progress

#17 #165305718 User should be presented with password reset link
  app.json
  package-lock.json
  src/App.jsx
  src/components/Nav.jsx
  src/components/home/__tests__/__snapshots__/homeNavBar.test.js.snap
  src/components/home/homeNavbar.jsx
  src/components/loginForm.jsx
  src/index.js
  src/redux/actions/__tests__/passwordConfirm.action.test.js
  src/redux/actions/__tests__/passwordReset.action.test.js
  src/redux/actions/index.js
  src/redux/actions/passwordConfirm.action.js
  src/redux/actions/passwordReset.action.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/passwordConfirm.reducer.test.js
  src/redux/reducers/__tests__/resetPasswordLink.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/passwordConfirm.reducer.js
  src/redux/reducers/resetPasswordLink.reducer.js
  src/services/api.js
  src/services/toastReusable.js
  src/styles/App.css
  src/views/home/__tests__/__snapshots__/homeContainer.test.js.snap
  src/views/home/__tests__/homeContainer.test.js
  src/views/index.js
  src/views/password_reset/PasswordResetConfirmContainer.jsx
  src/views/password_reset/PasswordResetContainer.jsx
  src/views/password_reset/__tests__/PasswordResetConfirmContainer.test.js
  src/views/password_reset/__tests__/PasswordResetContainer.test.js
  src/views/password_reset/__tests__/__snapshots__/PasswordResetConfirmContainer.test.js.snap
  src/views/password_reset/__tests__/__snapshots__/PasswordResetContainer.test.js.snap
  webpack.config.js
Labels: Finished

#21 #166523364 Fix Signup Modal
  src/App.jsx
  src/components/signup/FormComponent.jsx
  src/components/signup/SignupComponent.jsx
  src/components/signup/__tests__/__snapshots__/FormComponent.test.js.snap
  src/styles/style.css
Labels: Finished

#15 #165305720 Login with Twitter, Facebook, Google
  app.json
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login/LogInForm.jsx
  src/components/Login/LogInModal.jsx
  src/components/Login/SocialComponent.jsx
  src/components/Login/__tests__/SocialComponent.test.js
  src/components/Login/__tests__/__snapshots__/SocialComponent.test.js.snap
  src/components/home/HomeInfo.jsx
  src/components/home/HomeNavBar.jsx
  src/components/home/__tests__/HomeInfo.test.js
  src/components/home/__tests__/__snapshots__/HomeInfo.test.js.snap
  src/components/signup/SignupComponent.jsx
  src/components/signup/__tests__/SignupComponent.test.js
  src/redux/actions/SocialAuth.action.js
  src/redux/actions/__tests__/SocialAuth.action.test.js
  src/redux/constants/constants.js
  src/redux/reducers/SocialAuth.reducer.js
  src/redux/reducers/__tests__/SocialAuth.reducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/App.css
  src/styles/style.css
  src/views/home/HomeContainer.jsx
  src/views/home/__tests__/__snapshots__/homeContainer.test.js.snap
  src/views/home/__tests__/homeContainer.test.js
Labels: Reviews required

#23 #166537848 Fix SignUp
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login/LogInModal.jsx
  src/components/home/HomeInfo.jsx
  src/components/home/HomeNavBar.jsx
  src/components/home/__tests__/HomeInfo.test.js
  src/components/home/__tests__/__snapshots__/HomeInfo.test.js.snap
  src/components/home/__tests__/__snapshots__/homeNavBar.test.js.snap
  src/components/signup/FormComponent.jsx
  src/components/signup/SignupComponent.jsx
  src/components/signup/__tests__/FormComponent.test.js
  src/components/signup/__tests__/SignupComponent.test.js
  src/components/signup/__tests__/__snapshots__/FormComponent.test.js.snap
  src/components/signup/__tests__/__snapshots__/SignupComponent.test.js.snap
  src/redux/reducers/SignUp.reducer.js
  src/redux/reducers/__tests__/SignUpReducer.test.js
  src/services/FormValidators.js
  src/services/__tests__/FormValidators.test.js
  src/styles/style.css
  src/views/home/HomeContainer.jsx
  src/views/home/__tests__/__snapshots__/homeContainer.test.js.snap
  src/views/home/__tests__/homeContainer.test.js
Labels: Reviews required

#19 #165305721 View and Edit user profiles
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/App.jsx
  src/components/DummyPosts/NavBarDummy.jsx
  src/components/DummyPosts/__tests__/__snapshots__/NavBarDummy.test.js.snap
  src/components/profileNavbar.jsx
  src/components/profiles/EditProfile.jsx
  src/components/profiles/ViewProfile.jsx
  src/index.html
  src/redux/actions/__tests__/profile.actions.test.js
  src/redux/actions/profile.actions.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/profile.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/profile.reducer.js
  src/services/api.js
  src/services/images/cam.png
  src/services/images/profile.png
  src/styles/App.css
  src/views/profiles/EditProfile.jsx
  src/views/profiles/ViewProfile.jsx
  src/views/profiles/__tests__/EditProfile.test.js
  src/views/profiles/__tests__/ViewProfile.test.js
  src/views/profiles/__tests__/__snapshots__/EditProfile.test.js.snap
  src/views/profiles/__tests__/__snapshots__/ViewProfile.test.js.snap
  webpack.config.js
Labels: Reviews required

#24 #166538319 Fix Sign in page
  package-lock.json
  src/components/DummyPosts/DummyPosts.jsx
  src/components/DummyPosts/NavBarDummy.jsx
  src/components/DummyPosts/__tests__/__snapshots__/DummyPosts.test.js.snap
  src/components/Login/LogInForm.jsx
  src/components/Login/LogInModal.jsx
  src/components/Login/__tests__/LoginForm.test.js
  src/components/Login/__tests__/__snapshots__/LoginForm.test.js.snap
  src/components/home/HomeInfo.jsx
  src/components/home/__tests__/HomeInfo.test.js
  src/components/home/__tests__/__snapshots__/HomeInfo.test.js.snap
  src/redux/actions/SignIn.action.js
  src/redux/actions/SocialAuth.action.js
  src/redux/reducers/SignIn.reducer.js
  src/redux/reducers/__tests__/SignInReducer.test.js
  src/services/index.js
  src/styles/App.css
  src/styles/style.css
  src/views/home/HomeContainer.jsx
  src/views/home/__tests__/homeContainer.test.js
Labels: Reviews required

#25 #166604435 User logout or redirect to login if not logged in
  setupFiles.js
  src/App.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/__tests__/signedInLinks.test.js
  src/components/navbar/signedInLinks.jsx
  src/components/profiles/ViewProfile.jsx
  src/redux/actions/SignIn.action.js
  src/redux/actions/__tests__/SignIn.action.test.js
  src/redux/actions/__tests__/profile.actions.test.js
  src/redux/actions/profile.actions.js
  src/redux/constants/constants.js
  src/redux/reducers/SignIn.reducer.js
  src/redux/reducers/__tests__/SignInReducer.test.js
  src/services/__tests__/checkAuthentication.test.js
  src/services/api.js
  src/services/checkAuthentication.js
  src/services/history.js
  src/services/tokenDecoder.js
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/navigationbar/__tests__/LogoutNavigations.test.js
  src/views/navigationbar/__tests__/NavigationBarContainer.test.js
Labels: Reviews required

#18 #165305722 Articles CRUD
  jest.config.js
  package-lock.json
  package.json
  setupFiles.js
  src/App.jsx
  src/components/Articles.jsx
  src/components/Articles/PostFeed.jsx
  src/components/Articles/__tests__/PostFeed.test.js
  src/components/Articles/__tests__/Spinner.test.js
  src/components/Articles/__tests__/__snapshots__/PostFeed.test.js.snap
  src/components/Articles/__tests__/__snapshots__/Spinner.test.js.snap
  src/components/Articles/__tests__/__snapshots__/postForm.test.jsx.snap
  src/components/Articles/__tests__/postForm.test.jsx
  src/components/DummyPosts/DummyPosts.jsx
  src/components/DummyPosts/__tests__/DummyPosts.test.js
  src/components/DummyPosts/__tests__/__snapshots__/DummyPosts.test.js.snap
  src/components/__tests__/Articles.test.js
  src/components/__tests__/__snapshots__/Articles.test.js.snap
  src/components/home/HomeComponent.jsx
  src/components/home/PopularArticlesComponent.jsx
  src/components/home/TopRatedArticles.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
  src/components/home/__tests__/homeComponent.test.js
  src/components/homepagearticles/homePageArtclesComponent.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/signedInLinks.jsx
  src/index.html
  src/index.js
  src/redux/actions/__tests__/postActions.test.js
  src/redux/actions/postActions.js
  src/redux/constants/types.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/__tests__/PostReducer.test.js
  src/redux/reducers/__tests__/errorReducers.test.js
  src/redux/reducers/errorReducers.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/App.css
  src/views/Article/Spinner.jsx
  src/views/Article/__tests__/Spinner.test.js
  src/views/Article/__tests__/__snapshots__/Spinner.test.js.snap
  src/views/Article/__tests__/__snapshots__/post.tests.js.snap
  src/views/Article/__tests__/post.tests.js
  src/views/Article/post.jsx
  src/views/Article/spinner.gif
  src/views/Articles/PostForm.jsx
  src/views/Articles/PostItem.jsx
  src/views/Articles/Posts.jsx
  src/views/Articles/__tests__/PostForm.test.js
  src/views/Articles/__tests__/PostItem.test.js
  src/views/Articles/__tests__/__snapshots__/PostForm.test.js.snap
  src/views/Articles/__tests__/__snapshots__/PostItem.test.js.snap
  src/views/Articles/__tests__/__snapshots__/posts.test.jsx.snap
  src/views/Articles/__tests__/posts.test.jsx
  src/views/EditArticle/EditArticle.jsx
  src/views/EditArticle/__tests__/EditArticle.test.js
  src/views/EditArticle/__tests__/__snapshots__/EditArticle.test.js.snap
  src/views/navigationbar/NavigationBarContainer.jsx
Labels: Reviews required

#26 #165305732-Search and Filter Articles
  __mocks__/browserMock.js
  jest.config.js
  src/App.jsx
  src/components/navbar/renderedLinks.jsx
  src/components/search/ResultPageComponent.jsx
  src/components/search/SearchBarComponent.jsx
  src/components/search/SearchPageComponent.jsx
  src/components/search/__tests__/ResultPageComponent.test.js
  src/components/search/__tests__/SearchPageComponent.test.js
  src/redux/actions/Search.action.js
  src/redux/actions/__tests__/Search.action.test.js
  src/redux/constants/constants.js
  src/redux/reducers/Search.reducer.js
  src/redux/reducers/__tests__/Search.reducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/services/images/avatar.png
  src/styles/App.css
  src/styles/Search.css
  src/styles/style.css
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/navigationbar/__tests__/LogoutNavigations.test.js
  src/views/navigationbar/__tests__/NavigationBarContainer.test.js
  src/views/search/SearchBarContainer.jsx
  src/views/search/SearchPageContainer.jsx
  src/views/search/__tests__/SearchBarContainer.test.js
  src/views/search/__tests__/SearchPageContainer.test.js
Labels: Reviews required

#32 #166725748 Add 3D styling to both cards
  src/components/home/PopularArticlesComponent.jsx
  src/components/home/TopRatedArticles.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
Labels: Finished

#30 166697361 Fix Search Functionality
  __mocks__/browserMock.js
  jest.config.js
  src/components/search/ResultPageComponent.jsx
  src/components/search/SearchPageComponent.jsx
  src/components/search/__tests__/ResultPageComponent.test.js
  src/components/search/__tests__/SearchPageComponent.test.js
  src/components/search/constants.js
  src/styles/Search.css
  src/views/search/SearchBarContainer.jsx
  src/views/search/SearchPageContainer.jsx
  src/views/search/__tests__/SearchBarContainer.test.js
  src/views/search/__tests__/SearchPageContainer.test.js
Labels: Finished

#31 166719940-Fix Articles CRUD
  src/App.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/renderedLinks.jsx
  src/components/navbar/signedInLinks.jsx
  src/styles/style.css
  src/views/Article/post.jsx
Labels: Finished

#28 #166630607 Fix password reset
  package-lock.json
  src/components/NotFoundComponent.jsx
  src/components/__tests__/NotFoundComponent.test.jsx
  src/redux/actions/passwordReset.action.js
  src/services/toastReusable.js
  src/styles/App.css
  src/styles/style.css
  src/views/Article/__tests__/post.tests.js
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/password_reset/PasswordResetConfirmContainer.jsx
  src/views/password_reset/PasswordResetContainer.jsx
  src/views/password_reset/__tests__/__snapshots__/PasswordResetConfirmContainer.test.js.snap
  src/views/password_reset/__tests__/__snapshots__/PasswordResetContainer.test.js.snap
Labels: Finished

#29 #166604435 User logout and redirect to current logged in page
  __mocks__/browserMock.js
  jest.config.js
  package-lock.json
  src/components/profiles/EditProfile.jsx
  src/components/profiles/ViewProfile.jsx
  src/redux/actions/SignIn.action.js
  src/styles/App.css
  src/styles/Search.css
  src/views/profiles/__tests__/__snapshots__/EditProfile.test.js.snap
  src/views/profiles/__tests__/__snapshots__/ViewProfile.test.js.snap
Labels: Finished

#35 #166756346 Redesign the profile page
  src/App.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/signedInLinks.jsx
  src/components/profiles/FollowingComponent.jsx
  src/components/profiles/UserProfileComponent.jsx
  src/components/profiles/ViewProfile.jsx
  src/redux/actions/__tests__/userFollow.action.test.js
  src/redux/actions/profile.actions.js
  src/redux/actions/userFollow.action.js
  src/services/api.js
  src/styles/App.css
  src/views/profiles/FollowersContainer.jsx
  src/views/profiles/FollowingContainer.jsx
  src/views/profiles/OtheUserContainer.jsx
  src/views/profiles/ProfileArticlesContainer.jsx
  src/views/profiles/ProfileArticlesFeed.jsx
  src/views/profiles/ProfileArticlesItems.jsx
  src/views/profiles/ViewProfile.jsx
  src/views/profiles/__tests__/OtherUserContainer.test.js
  src/views/profiles/__tests__/PostArticlesItems.test.js
  src/views/profiles/__tests__/ProfileArticlesFeed.test.js
  src/views/profiles/__tests__/ViewProfile.test.js
  src/views/profiles/__tests__/__snapshots__/OtherUserContainer.test.js.snap
  src/views/profiles/__tests__/__snapshots__/PostArticlesItems.test.js.snap
  src/views/profiles/__tests__/__snapshots__/ProfileArticlesFeed.test.js.snap
  src/views/profiles/__tests__/__snapshots__/ViewProfile.test.js.snap
Labels: Finished

#33 #165305726 Like and Dislike Article
  src/App.jsx
  src/App.test.jsx
  src/components/Likes/LikesComponent.jsx
  src/components/Likes/PropmptComponent.jsx
  src/components/Likes/__tests__/LikesComponent.test.js
  src/components/Likes/__tests__/PromptComponent.test.js
  src/redux/actions/Likes.action.js
  src/redux/actions/Prompt.action.js
  src/redux/actions/SignIn.action.js
  src/redux/actions/__tests__/Likes.action.test.js
  src/redux/actions/__tests__/Prompt.action.test.js
  src/redux/actions/app.action.js
  src/redux/actions/postActions.js
  src/redux/constants/constants.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/Prompt.reducer.js
  src/redux/reducers/SignIn.reducer.js
  src/redux/reducers/__tests__/PostReducer.test.js
  src/redux/reducers/__tests__/Prompt.reducer.test.js
  src/redux/reducers/__tests__/SignInReducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/Likes.css
  src/styles/style.css
  src/views/Article/__tests__/post.tests.js
  src/views/Article/post.jsx
  src/views/Likes/LikesContainer.jsx
  src/views/Likes/__tests__/LikesContainer.test.js
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/navigationbar/__tests__/LogoutNavigations.test.js
  src/views/navigationbar/__tests__/NavigationBarContainer.test.js
  src/views/search/__tests__/SearchBarContainer.test.js
Labels: Finished

#34 #165305727 Add Tags to Articles
  package-lock.json
  package.json
  src/styles/Tags.css
  src/styles/style.css
  src/views/Article/post.jsx
  src/views/Articles/PostForm.jsx
  src/views/Articles/__tests__/PostForm.test.js
Labels: Finished

#39 #165305724 User can comment on articles
  src/components/comments/CommentsComponent.jsx
  src/components/comments/CreateCommentComponent.jsx
  src/components/comments/CreateReplyComponent.jsx
  src/components/comments/__tests__/CommentsComponent.test.js
  src/components/comments/__tests__/CreateCommentComponent.test.js
  src/components/comments/__tests__/CreateReplyComponent.test.js
  src/components/comments/__tests__/__snapshots__/CommentsComponent.test.js.snap
  src/components/comments/__tests__/__snapshots__/CreateCommentComponent.test.js.snap
  src/components/comments/__tests__/__snapshots__/CreateReplyComponent.test.js.snap
  src/index.html
  src/index.js
  src/redux/actions/Comments.action.js
  src/redux/actions/__tests__/Comments.action.test.js
  src/redux/constants/constants.js
  src/redux/reducers/Comments.reducer.js
  src/redux/reducers/__tests__/Comments.reducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/comments.scss
  src/styles/variables.scss
  src/views/Article/post.jsx
  src/views/comments/CommentsContainer.jsx
  src/views/comments/RepliesContainer.jsx
  src/views/comments/__tests__/CommentsContainer.test.js
  src/views/comments/__tests__/RepliesContainer.test.js
  src/views/comments/__tests__/__snapshots__/CommentsContainer.test.js.snap
  src/views/comments/__tests__/__snapshots__/RepliesContainer.test.js.snap
  webpack.config.js
Labels: Reviews required

#38 #1653057257 Add Pagination to Articles
  package-lock.json
  package.json
  src/App.test.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
  src/components/home/__tests__/homeComponent.test.js
  src/redux/actions/__tests__/postActions.test.js
  src/redux/actions/postActions.js
  src/redux/constants/types.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/__tests__/PostReducer.test.js
  src/redux/store.js
  src/services/api.js
  src/styles/pagination.css
  src/views/Article/post.jsx
  src/views/Articles/Posts.jsx
  src/views/Articles/__tests__/posts.test.jsx
  src/views/Pagination/PaginationContainer.jsx
Labels: Finished

#40 #165305728 User can share articles on social media
  package-lock.json
  src/components/share_modal/SVG_buttons/FacebookButtonComponent.jsx
  src/components/share_modal/SVG_buttons/MailButtonComponent.jsx
  src/components/share_modal/SVG_buttons/TwitterButtonComponent.jsx
  src/components/share_modal/SVG_buttons/__tests__/FacebookButtonComponent.test.js
  src/components/share_modal/SVG_buttons/__tests__/MailButtonComponent.test.js
  src/components/share_modal/SVG_buttons/__tests__/TwitterButtonComponent.test.js
  src/components/share_modal/SVG_buttons/__tests__/__snapshots__/FacebookButtonComponent.test.js.snap
  src/components/share_modal/SVG_buttons/__tests__/__snapshots__/MailButtonComponent.test.js.snap
  src/components/share_modal/SVG_buttons/__tests__/__snapshots__/TwitterButtonComponent.test.js.snap
  src/components/share_modal/ShareArticleComponent.jsx
  src/components/share_modal/ShareArticlesButtonsComponent.jsx
  src/components/share_modal/__tests__/ShareArticleComponent.test.js
  src/components/share_modal/__tests__/ShareArticlesButtonsComponent.test.js
  src/components/share_modal/__tests__/__snapshots__/ShareArticleComponent.test.js.snap
  src/components/share_modal/__tests__/__snapshots__/ShareArticlesButtonsComponent.test.js.snap
  src/redux/actions/postActions.js
  src/services/images/mail.png
  src/styles/App.css
  src/views/Article/post.jsx
Labels: Finished

#44 #166843522 Fix Likes and Dislikes On Articles
  src/components/Likes/LikesComponent.jsx
  src/styles/Likes.css
Labels: Finished

#48 166871325 Implement feedback on share modal
  src/components/share_modal/SVG_buttons/FacebookButtonComponent.jsx
  src/components/share_modal/SVG_buttons/MailButtonComponent.jsx
  src/styles/App.css
Labels: Reviews required

#45 #166860362 Fix tags and pagination
  src/components/home/HomeComponent.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
  src/styles/pagination.scss
  src/views/Article/post.jsx
  src/views/Articles/Posts.jsx
  src/views/EditArticle/EditArticle.jsx
  src/views/EditArticle/__tests__/EditArticle.test.js
  src/views/Pagination/PaginationContainer.jsx
Labels: Finished

#36 #165305723 Rate articles
  package-lock.json
  package.json
  src/App.test.jsx
  src/components/RateArticles/RateArtcles.jsx
  src/components/RateArticles/__tests__/RateArticles.test.js
  src/index.html
  src/redux/actions/__tests__/Rate.action.test.js
  src/redux/actions/rateArtcicles.js
  src/redux/constants/types.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/SignIn.reducer.js
  src/redux/reducers/__tests__/SignInReducer.test.js
  src/services/api.js
  src/styles/App.css
  src/styles/style.css
  src/views/Article/post.jsx
  src/views/Articles/Posts.jsx
  src/views/Articles/__tests__/posts.test.jsx
Labels: Finished

#37 #165305730 View notifications
  src/App.test.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/__tests__/signedInLinks.test.js
  src/components/navbar/signedInLinks.jsx
  src/redux/actions/__tests__/notificatifications.action.test.js
  src/redux/actions/notifications.action.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/notifications.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/notifications.reducer.js
  src/services/api.js
  src/styles/App.css
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/navigationbar/__tests__/LogoutNavigations.test.js
  src/views/navigationbar/__tests__/NavigationBarContainer.test.js
Labels: Reviews required

#50 #166902649 Update Readme file
  README.md
Labels: Reviews required

#43 #165305731 Opt in/out of notifications
  package-lock.json
  package.json
  src/App.test.jsx
  src/components/navbar/__tests__/__snapshots__/signedInLinks.test.js.snap
  src/components/navbar/__tests__/signedInLinks.test.js
  src/components/navbar/signedInLinks.jsx
  src/components/notifications/NotificationComponent.jsx
  src/redux/actions/__tests__/Notifications.action.test.js
  src/redux/actions/notifications.action.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/Notifications.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/notifications.reducer.js
  src/services/api.js
  src/services/images/email.png
  src/services/images/push.png
  src/styles/App.css
  src/views/navigationbar/NavigationBarContainer.jsx
  src/views/navigationbar/__tests__/LogoutNavigations.test.js
  src/views/navigationbar/__tests__/NavigationBarContainer.test.js
Labels: Reviews required

#51 #165305735 List Bookmarks
  package-lock.json
  src/components/profiles/UserProfileComponent.jsx
  src/components/profiles/ViewProfile.jsx
  src/index.html
  src/redux/actions/__tests__/ListBookmarks.actions.test.js
  src/redux/actions/__tests__/userFollow.action.test.js
  src/redux/actions/listBookmarks.actions.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/ListBookmarks.reducer.test.js
  src/redux/reducers/index.js
  src/redux/reducers/listBookmarks.reducer.js
  src/services/api.js
  src/styles/App.css
  src/views/profiles/ListBookmarksContainer.jsx
  src/views/profiles/__tests__/ViewProfile.test.js
  src/views/profiles/__tests__/__snapshots__/ViewProfile.test.js.snap
Labels: Finished

#54 #166923155 View popular articles
  package-lock.json
  src/App.test.jsx
  src/components/home/HomeComponent.jsx
  src/components/home/PopularArticlesComponent.jsx
  src/components/home/TopRatedArticles.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
  src/components/home/__tests__/homeComponent.test.js
  src/redux/actions/__tests__/allArticles.action.test.js
  src/redux/actions/allArticles.action.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/allArticles.reducer.test.js
  src/redux/reducers/allArticles.reducer.js
  src/redux/reducers/index.js
  src/services/api.js
  src/services/sortArticles.js
  src/styles/App.css
  src/views/Articles/ArticleDataContainer.jsx
  src/views/Articles/PopularArticlesContainer.jsx
  src/views/Articles/__tests__/ArticleContainer.test.js
Labels: Reviews required

#53 #166923038 View top rated articles
  package-lock.json
  src/App.test.jsx
  src/components/home/HomeComponent.jsx
  src/components/home/TopRatedArticles.jsx
  src/components/home/__tests__/__snapshots__/homeComponent.test.js.snap
  src/components/home/__tests__/homeComponent.test.js
  src/redux/actions/__tests__/allArticles.action.test.js
  src/redux/actions/allArticles.action.js
  src/redux/constants/constants.js
  src/redux/reducers/__tests__/allArticles.reducer.test.js
  src/redux/reducers/allArticles.reducer.js
  src/redux/reducers/index.js
  src/services/api.js
  src/services/sortArticles.js
  src/styles/App.css
  src/views/Articles/ArticleDataContainer.jsx
  src/views/Articles/__tests__/ArticleContainer.test.js
Labels: Finished, Reviews required

#47 #165305737 HighLight Articles
  package-lock.json
  package.json
  src/components/highlight/CommentComponent.jsx
  src/components/highlight/HighlightComponent.jsx
  src/redux/actions/__tests__/Highlight.actions.test.js
  src/redux/actions/highlight.action.js
  src/redux/constants/constants.js
  src/redux/reducers/Highlight.reducer.js
  src/redux/reducers/HighlightModal.reducer.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/__tests__/Highlight.reducer.test.js
  src/redux/reducers/__tests__/HighlightModal.reducer.test.js
  src/redux/reducers/__tests__/PostReducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/style.css
  src/views/Article/TestObjects.js
  src/views/Article/__tests__/__snapshots__/post.tests.js.snap
  src/views/Article/__tests__/post.tests.js
  src/views/Article/post.jsx
  src/views/highlight/HighlightContainer.jsx
Labels: Finished

#49 #165305736-Report an Article
  package-lock.json
  src/App.jsx
  src/components/profiles/ViewProfile.jsx
  src/redux/actions/__tests__/postActions.test.js
  src/redux/actions/postActions.js
  src/redux/constants/types.js
  src/redux/reducers/PostReducer.js
  src/redux/reducers/__tests__/PostReducer.test.js
  src/services/api.js
  src/views/Article/post.jsx
  src/views/EditArticle/EditArticle.jsx
  src/views/Report/ReportContainer.jsx
  src/views/Report/ReportsContainer.jsx
  src/views/Report/__tests__/ReportContainer.test.jsx
  src/views/Report/__tests__/ReportsContainer.test.jsx
  src/views/Report/__tests__/__snapshots__/ReportContainer.test.jsx.snap
  src/views/Report/__tests__/__snapshots__/ReportsContainer.test.jsx.snap
  src/views/profiles/__tests__/__snapshots__/ViewProfile.test.js.snap
Labels: Finished

#55 #165305734 Bookmark articles for reading later
  package-lock.json
  src/components/bookmark/BookmarkComponent.jsx
  src/components/bookmark/__tests__/BookmarkComponent.test.js
  src/components/bookmark/__tests__/__snapshots__/BookmarkComponent.test.js.snap
  src/redux/actions/Bookmark.actions.js
  src/redux/actions/UnBookmark.actions.js
  src/redux/actions/__tests__/Bookmark.actions.test.js
  src/redux/actions/__tests__/UnBookmark.actions.test.js
  src/redux/constants/constants.js
  src/redux/reducers/Bookmark.reducer.js
  src/redux/reducers/UnBookmark.reducer.js
  src/redux/reducers/__tests__/Bookmark.reducer.test.js
  src/redux/reducers/__tests__/UnBookmark.reducer.test.js
  src/redux/reducers/index.js
  src/services/api.js
  src/styles/App.css
  src/views/Article/post.jsx
  src/views/Articles/PostForm.jsx
  src/views/Articles/Posts.jsx
  src/views/bookmark/BookmarkContainer.jsx
  src/views/bookmark/__tests__/BookmarkContainer.test.js
  src/views/bookmark/__tests__/__snapshots__/BookmarkContainer.test.js.snap
Labels: Reviews required
